PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZIAL_T_LOG_CNF-DFLT_OBJECT .
    FIELD ZIAL_T_LOG_CNF-DFLT_SUBOBJECT .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
  module detail_pai.
 endchain.
