PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZIAL_V_LOG_CONF CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZIAL_V_LOG_CONF-OBJECT .
    FIELD ZIAL_V_LOG_CONF-SUBOBJECT .
    FIELD ZIAL_V_LOG_CONF-UNAME .
    FIELD ZIAL_V_LOG_CONF-DETAIL_LEVEL .
    FIELD ZIAL_V_LOG_CONF-LEVEL_LOG_CALLSTACK .
    FIELD ZIAL_V_LOG_CONF-VALIDITY_PERIOD .
    FIELD ZIAL_V_LOG_CONF-OBJTXT .
    FIELD ZIAL_V_LOG_CONF-SUBOBJTXT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZIAL_V_LOG_CONF ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZIAL_V_LOG_CONF-OBJECT .
    FIELD ZIAL_V_LOG_CONF-SUBOBJECT .
    FIELD ZIAL_V_LOG_CONF-UNAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
