*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZIAL_V_LOG_CONF.................................*
FORM GET_DATA_ZIAL_V_LOG_CONF.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZIAL_T_LOG_CONF WHERE
(VIM_WHERETAB) .
    CLEAR ZIAL_V_LOG_CONF .
ZIAL_V_LOG_CONF-MANDT =
ZIAL_T_LOG_CONF-MANDT .
ZIAL_V_LOG_CONF-OBJECT =
ZIAL_T_LOG_CONF-OBJECT .
ZIAL_V_LOG_CONF-SUBOBJECT =
ZIAL_T_LOG_CONF-SUBOBJECT .
ZIAL_V_LOG_CONF-UNAME =
ZIAL_T_LOG_CONF-UNAME .
ZIAL_V_LOG_CONF-DETAIL_LEVEL =
ZIAL_T_LOG_CONF-DETAIL_LEVEL .
ZIAL_V_LOG_CONF-LEVEL_LOG_CALLSTACK =
ZIAL_T_LOG_CONF-LEVEL_LOG_CALLSTACK .
ZIAL_V_LOG_CONF-VALIDITY_PERIOD =
ZIAL_T_LOG_CONF-VALIDITY_PERIOD .
    SELECT SINGLE * FROM BALOBJ WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALOBJT WHERE
OBJECT = BALOBJ-OBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-OBJTXT =
BALOBJT-OBJTXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM BALSUB WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT AND
SUBOBJECT = ZIAL_T_LOG_CONF-SUBOBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALSUBT WHERE
OBJECT = BALSUB-OBJECT AND
SUBOBJECT = BALSUB-SUBOBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-SUBOBJTXT =
BALSUBT-SUBOBJTXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZIAL_V_LOG_CONF.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZIAL_V_LOG_CONF .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZIAL_V_LOG_CONF.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZIAL_V_LOG_CONF-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZIAL_T_LOG_CONF WHERE
  OBJECT = ZIAL_V_LOG_CONF-OBJECT AND
  SUBOBJECT = ZIAL_V_LOG_CONF-SUBOBJECT AND
  UNAME = ZIAL_V_LOG_CONF-UNAME .
    IF SY-SUBRC = 0.
    DELETE ZIAL_T_LOG_CONF .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZIAL_T_LOG_CONF WHERE
  OBJECT = ZIAL_V_LOG_CONF-OBJECT AND
  SUBOBJECT = ZIAL_V_LOG_CONF-SUBOBJECT AND
  UNAME = ZIAL_V_LOG_CONF-UNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZIAL_T_LOG_CONF.
    ENDIF.
ZIAL_T_LOG_CONF-MANDT =
ZIAL_V_LOG_CONF-MANDT .
ZIAL_T_LOG_CONF-OBJECT =
ZIAL_V_LOG_CONF-OBJECT .
ZIAL_T_LOG_CONF-SUBOBJECT =
ZIAL_V_LOG_CONF-SUBOBJECT .
ZIAL_T_LOG_CONF-UNAME =
ZIAL_V_LOG_CONF-UNAME .
ZIAL_T_LOG_CONF-DETAIL_LEVEL =
ZIAL_V_LOG_CONF-DETAIL_LEVEL .
ZIAL_T_LOG_CONF-LEVEL_LOG_CALLSTACK =
ZIAL_V_LOG_CONF-LEVEL_LOG_CALLSTACK .
ZIAL_T_LOG_CONF-VALIDITY_PERIOD =
ZIAL_V_LOG_CONF-VALIDITY_PERIOD .
    IF SY-SUBRC = 0.
    UPDATE ZIAL_T_LOG_CONF ##WARN_OK.
    ELSE.
    INSERT ZIAL_T_LOG_CONF .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZIAL_V_LOG_CONF-UPD_FLAG,
STATUS_ZIAL_V_LOG_CONF-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZIAL_V_LOG_CONF.
  SELECT SINGLE * FROM ZIAL_T_LOG_CONF WHERE
OBJECT = ZIAL_V_LOG_CONF-OBJECT AND
SUBOBJECT = ZIAL_V_LOG_CONF-SUBOBJECT AND
UNAME = ZIAL_V_LOG_CONF-UNAME .
ZIAL_V_LOG_CONF-MANDT =
ZIAL_T_LOG_CONF-MANDT .
ZIAL_V_LOG_CONF-OBJECT =
ZIAL_T_LOG_CONF-OBJECT .
ZIAL_V_LOG_CONF-SUBOBJECT =
ZIAL_T_LOG_CONF-SUBOBJECT .
ZIAL_V_LOG_CONF-UNAME =
ZIAL_T_LOG_CONF-UNAME .
ZIAL_V_LOG_CONF-DETAIL_LEVEL =
ZIAL_T_LOG_CONF-DETAIL_LEVEL .
ZIAL_V_LOG_CONF-LEVEL_LOG_CALLSTACK =
ZIAL_T_LOG_CONF-LEVEL_LOG_CALLSTACK .
ZIAL_V_LOG_CONF-VALIDITY_PERIOD =
ZIAL_T_LOG_CONF-VALIDITY_PERIOD .
    SELECT SINGLE * FROM BALOBJ WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALOBJT WHERE
OBJECT = BALOBJ-OBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-OBJTXT =
BALOBJT-OBJTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZIAL_V_LOG_CONF-OBJTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZIAL_V_LOG_CONF-OBJTXT .
    ENDIF.
    SELECT SINGLE * FROM BALSUB WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT AND
SUBOBJECT = ZIAL_T_LOG_CONF-SUBOBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALSUBT WHERE
OBJECT = BALSUB-OBJECT AND
SUBOBJECT = BALSUB-SUBOBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-SUBOBJTXT =
BALSUBT-SUBOBJTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZIAL_V_LOG_CONF-SUBOBJTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZIAL_V_LOG_CONF-SUBOBJTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZIAL_V_LOG_CONF USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZIAL_V_LOG_CONF-OBJECT TO
ZIAL_T_LOG_CONF-OBJECT .
MOVE ZIAL_V_LOG_CONF-SUBOBJECT TO
ZIAL_T_LOG_CONF-SUBOBJECT .
MOVE ZIAL_V_LOG_CONF-UNAME TO
ZIAL_T_LOG_CONF-UNAME .
MOVE ZIAL_V_LOG_CONF-MANDT TO
ZIAL_T_LOG_CONF-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZIAL_T_LOG_CONF'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZIAL_T_LOG_CONF TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZIAL_T_LOG_CONF'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZIAL_V_LOG_CONF USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZIAL_T_LOG_CONF-MANDT =
ZIAL_V_LOG_CONF-MANDT .
ZIAL_T_LOG_CONF-OBJECT =
ZIAL_V_LOG_CONF-OBJECT .
ZIAL_T_LOG_CONF-SUBOBJECT =
ZIAL_V_LOG_CONF-SUBOBJECT .
ZIAL_T_LOG_CONF-UNAME =
ZIAL_V_LOG_CONF-UNAME .
ZIAL_T_LOG_CONF-DETAIL_LEVEL =
ZIAL_V_LOG_CONF-DETAIL_LEVEL .
ZIAL_T_LOG_CONF-LEVEL_LOG_CALLSTACK =
ZIAL_V_LOG_CONF-LEVEL_LOG_CALLSTACK .
ZIAL_T_LOG_CONF-VALIDITY_PERIOD =
ZIAL_V_LOG_CONF-VALIDITY_PERIOD .
    SELECT SINGLE * FROM BALOBJ WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALOBJT WHERE
OBJECT = BALOBJ-OBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-OBJTXT =
BALOBJT-OBJTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZIAL_V_LOG_CONF-OBJTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZIAL_V_LOG_CONF-OBJTXT .
    ENDIF.
    SELECT SINGLE * FROM BALSUB WHERE
OBJECT = ZIAL_T_LOG_CONF-OBJECT AND
SUBOBJECT = ZIAL_T_LOG_CONF-SUBOBJECT .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM BALSUBT WHERE
OBJECT = BALSUB-OBJECT AND
SUBOBJECT = BALSUB-SUBOBJECT AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZIAL_V_LOG_CONF-SUBOBJTXT =
BALSUBT-SUBOBJTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZIAL_V_LOG_CONF-SUBOBJTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZIAL_V_LOG_CONF-SUBOBJTXT .
    ENDIF.
ENDFORM.
